# Generated by Django 5.1.4 on 2025-01-18 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subject'),
        ),
    ]
