# Generated by Django 5.1.4 on 2025-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_school_studentreport_subjectgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='total_attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='total_attendance_points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SubjectGrade',
        ),
    ]
