# Generated by Django 5.1.4 on 2025-01-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_submission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
