# Generated by Django 5.1.4 on 2025-01-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
